id: apache5
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: apache5
    containers:
      - name: apache5
        image: francois/apache-hostname:0.1.0
        cpu: 100
        ports:
          - containerPort: 80
            hostPort: 10001
labels: 
  name: apache5
  service: http-pods
