id: apache2
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: apache2
    containers:
      - name: apache2
        image: francois/apache-hostname:0.1.0
        cpu: 100
        ports:
          - containerPort: 80
            hostPort: 80
labels: 
  name: apache2
  service: http-pods
