id: apache4
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: apache4
    containers:
      - name: apache4
        image: francois/apache-hostname:0.1.0
        cpu: 100
        ports:
          - containerPort: 80
            hostPort: 10000
labels: 
  name: apache4
  service: http-pods
