id: apache3
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest: 
    version: v1beta1
    id: apache3
    containers:
      - name: apache3
        image: francois/apache-hostname:0.1.0
        cpu: 100
        ports:
          - containerPort: 80
            hostPort: 80
labels: 
  name: apache3
  service: http-pods
